# result of flickr.person.public_photos
--- !ruby/object:Flickr::Photos::Photo 
farm: "3"
flickr: *id001
geo: 
icon_server: 
id: "4466841537"
is_family: "0"
is_friend: "0"
is_public: "1"
license_id: 5
machine_tags: ""
media: photo
o_dims: 
original_format: jpg
owner: 99884191@N00
owner_name: TomK32
secret: f6b67238d7
server: "2740"
tags: ""
taken_at: 2010-03-27 17:04:32 +01:00
title: kleine geldtasche 3
updated_at: 2010-03-28 16:40:23 +02:00
uploaded_at: 2010-03-27 18:06:42 +01:00
views: 7