#!/bin/sh

DAEMON=bundle exec ./script/navvy
APP_DIR="/var/www/photostre.am/current/"
export RAILS_ENV=production

case "$1" in
    start)
        echo -n "Starting navvy "
        cd $APP_DIR
        $DAEMON start
        ;;
    stop)
        echo -n "Shutting down navvy "
        cd $APP_DIR
        $DAEMON stop
        ;;
    restart)
        $0 stop
        $0 start
        ;;
esac