defaults: &defaults
  host: localhost

test:
  <<: *defaults
  database: photostream_test

development:
  <<: *defaults
  database: photostream_development

production:
  <<: *defaults
  database: photostream_production