#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
Navvy.configuration do |config|
  config.logger = Rails.logger
end
Navvy::Worker.daemonize
